version: '3.1'
 
services:
    teamcity:
        image: jetbrains/teamcity-server:latest
        volumes:
          - teamcity-server-datadir:/data/teamcity-server/datadir
          - teamcity-server-logs:/opt/teamcity/logs
        ports:
            - 8111:8111
    teamcity-jetbrains:
        image: jetbrains/teamcity-agent:latest
        environment:
            SERVER_URL: http://teamcity:8111
        volumes:
          - teamcity-agent-conf:/data/teamcity_agent/conf
          - /var/run/docker.sock:/var/run/docker.sock
    teamcity-lunarfrog:
        image: lunarfrog/teamcity-agent-dotnet:latest
        environment:
            SERVER_URL: http://teamcity:8111
        volumes:
            - /srv/teamcity/agents/001/conf:/data/teamcity_agent/conf
    teamcity-minimal-agent:
        image: jetbrains/teamcity-minimal-agent
        environment:
            SERVER_URL: http://teamcity:8111
        volumes:
            - /srv/teamcity/agents/001/conf:/data/teamcity_agent/conf
    teamcity-codemazeblog:
        image: codemazeblog/teamcity-agent-docker-compose:latest
        environment:
          SERVER_URL: http://teamcity:8111
        volumes:
          - teamcity-agent-conf:/data/teamcity_agent/conf
          - /opt/buildagent/work:/opt/buildagent/work
          - /opt/buildagent/temp:/opt/buildagent/temp
          - /var/run/docker.sock:/var/run/docker.sock
    
volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
  teamcity-agent-conf: